version: "3.9"

services:
  db:
    image: postgres:16
    container_name: excallidraw
    environment:
      POSTGRES_USER: chrollo
      POSTGRES_PASSWORD: chrollo
      POSTGRES_DB: excallidraw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pgdata:
  minio_data:
